### ISSUE TITLE
Init fails

### ISSUE THREAD

**Issue by mrdgo** [ms-jpq/coq.thirdparty#18]
On setup, I get an error:
`packer.nvim: Error running config for coq_nvim: ...ite/pack/packer/start/coq.thirdparty/lua/coq_3p/init.lua:33: Expected lua string`

**Comment by ms-jpq** [comment]
I fixed this message, you should get a more descriptive error now, if there is something wrong

**Comment by ms-jpq** [comment]
Closing because there is nothing I can do for this non-specific error, you probably had a mis-configuration, but since the error is so bad, i can't diagnosis it
